import type { AppLanguageCode } from "@/shared/lib/languages";

export type UiStrings = {
  readonly appName: string;
  readonly tagline: string;
  readonly speakLabel: string;
  readonly speakHint: string;
  readonly photoLabel: string;
  readonly photoHint: string;
  readonly emptyState: string;
  readonly listening: string;
  readonly thinking: string;
  readonly connected: string;
};

export const UI_STRINGS: Record<AppLanguageCode, UiStrings> = {
  "en-IN": {
    appName: "Nyaya-Dost",
    tagline: "Hear your legal rights, in your own language",
    speakLabel: "Speak",
    speakHint: "Tap and speak your question",
    photoLabel: "Take a Photo",
    photoHint: "Photograph the notice",
    emptyState: "Tap the record button below and speak your question",
    listening: "Listening…",
    thinking: "Checking the law…",
    connected: "CONNECTED",
  },
  "hi-IN": {
    appName: "न्याय-दोस्त",
    tagline: "अपना कानूनी हक़, अपनी भाषा में सुनिए",
    speakLabel: "बोलिए",
    speakHint: "टैप करें और अपना सवाल बोलें",
    photoLabel: "फ़ोटो लें",
    photoHint: "नोटिस की फोटो लें",
    emptyState: "रिकॉर्ड बटन दबाएँ और अपना सवाल बोलें",
    listening: "सुन रहा हूँ…",
    thinking: "जाँच हो रही है…",
    connected: "CONNECTED",
  },
  "bn-IN": {
    appName: "ন্যায়-দোস্ত",
    tagline: "আপনার আইনি অধিকার, আপনার নিজের ভাষায় শুনুন",
    speakLabel: "বলুন",
    speakHint: "ট্যাপ করে আপনার প্রশ্ন বলুন",
    photoLabel: "ছবি তুলুন",
    photoHint: "নোটিসের ছবি তুলুন",
    emptyState: "নিচের রেকর্ড বোতাম চেপে আপনার প্রশ্ন বলুন",
    listening: "শুনছি…",
    thinking: "আইন যাচাই করা হচ্ছে…",
    connected: "CONNECTED",
  },
  "gu-IN": {
    appName: "ન્યાય-દોસ્ત",
    tagline: "તમારા કાનૂની અધિકારો, તમારી પોતાની ભાષામાં સાંભળો",
    speakLabel: "બોલો",
    speakHint: "ટેપ કરો અને તમારો પ્રશ્ન બોલો",
    photoLabel: "ફોટો લો",
    photoHint: "નોટિસનો ફોટો લો",
    emptyState: "નીચેનું રેકોર્ડ બટન દબાવીને તમારો પ્રશ્ન બોલો",
    listening: "સાંભળી રહ્યા છીએ…",
    thinking: "કાયદો તપાસી રહ્યા છીએ…",
    connected: "CONNECTED",
  },
  "kn-IN": {
    appName: "ನ್ಯಾಯ-ದೋಸ್ತ್",
    tagline: "ನಿಮ್ಮ ಕಾನೂನು ಹಕ್ಕುಗಳನ್ನು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಕೇಳಿ",
    speakLabel: "ಮಾತನಾಡಿ",
    speakHint: "ಟ್ಯಾಪ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ",
    photoLabel: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    photoHint: "ನೋಟಿಸ್‌ನ ಫೋಟೋ ತೆಗೆಯಿರಿ",
    emptyState: "ಕೆಳಗಿನ ರೆಕಾರ್ಡ್ ಬಟನ್ ಒತ್ತಿ ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಕೇಳಿ",
    listening: "ಕೇಳುತ್ತಿದ್ದೇನೆ…",
    thinking: "ಕಾನೂನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…",
    connected: "CONNECTED",
  },
  "ml-IN": {
    appName: "ന്യായ-ദോസ്ത്",
    tagline: "നിങ്ങളുടെ നിയമപരമായ അവകാശങ്ങൾ, നിങ്ങളുടെ സ്വന്തം ഭാഷയിൽ കേൾക്കൂ",
    speakLabel: "സംസാരിക്കൂ",
    speakHint: "ടാപ്പ് ചെയ്ത് നിങ്ങളുടെ ചോദ്യം പറയൂ",
    photoLabel: "ഫോട്ടോ എടുക്കൂ",
    photoHint: "നോട്ടീസിന്റെ ഫോട്ടോ എടുക്കൂ",
    emptyState: "താഴെയുള്ള റെക്കോർഡ് ബട്ടൺ അമർത്തി നിങ്ങളുടെ ചോദ്യം പറയൂ",
    listening: "കേൾക്കുന്നു…",
    thinking: "നിയമം പരിശോധിക്കുന്നു…",
    connected: "CONNECTED",
  },
  "mr-IN": {
    appName: "न्याय-दोस्त",
    tagline: "आपले कायदेशीर हक्क, आपल्या भाषेत ऐका",
    speakLabel: "बोला",
    speakHint: "टॅप करा आणि आपला प्रश्न बोला",
    photoLabel: "फोटो घ्या",
    photoHint: "नोटिसचा फोटो घ्या",
    emptyState: "खालील रेकॉर्ड बटण दाबून आपला प्रश्न बोला",
    listening: "ऐकत आहे…",
    thinking: "कायदा तपासत आहे…",
    connected: "CONNECTED",
  },
  "od-IN": {
    appName: "ନ୍ୟାୟ-ଦୋସ୍ତ",
    tagline: "ଆପଣଙ୍କ ଆଇନଗତ ଅଧିକାର, ଆପଣଙ୍କ ନିଜ ଭାଷାରେ ଶୁଣନ୍ତୁ",
    speakLabel: "କୁହନ୍ତୁ",
    speakHint: "ଟ୍ୟାପ୍ କରି ଆପଣଙ୍କ ପ୍ରଶ୍ନ କୁହନ୍ତୁ",
    photoLabel: "ଫଟୋ ନିଅନ୍ତୁ",
    photoHint: "ନୋଟିସ୍‌ର ଫଟୋ ନିଅନ୍ତୁ",
    emptyState: "ତଳେ ଥିବା ରେକର୍ଡ ବଟନ୍ ଦବାଇ ଆପଣଙ୍କ ପ୍ରଶ୍ନ କୁହନ୍ତୁ",
    listening: "ଶୁଣୁଛି…",
    thinking: "ଆଇନ ଯାଞ୍ଚ ହେଉଛି…",
    connected: "CONNECTED",
  },
  "pa-IN": {
    appName: "ਨਿਆਂ-ਦੋਸਤ",
    tagline: "ਆਪਣੇ ਕਾਨੂੰਨੀ ਅਧਿਕਾਰ, ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸੁਣੋ",
    speakLabel: "ਬੋਲੋ",
    speakHint: "ਟੈਪ ਕਰੋ ਅਤੇ ਆਪਣਾ ਸਵਾਲ ਬੋਲੋ",
    photoLabel: "ਫੋਟੋ ਲਓ",
    photoHint: "ਨੋਟਿਸ ਦੀ ਫੋਟੋ ਲਓ",
    emptyState: "ਹੇਠਾਂ ਦਿੱਤਾ ਰਿਕਾਰਡ ਬਟਨ ਦਬਾ ਕੇ ਆਪਣਾ ਸਵਾਲ ਬੋਲੋ",
    listening: "ਸੁਣ ਰਿਹਾ ਹਾਂ…",
    thinking: "ਕਾਨੂੰਨ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ…",
    connected: "CONNECTED",
  },
  "ta-IN": {
    appName: "நியாய-தோஸ்த்",
    tagline: "உங்கள் சட்ட உரிமைகளை உங்கள் மொழியில் கேளுங்கள்",
    speakLabel: "பேசுங்கள்",
    speakHint: "தட்டி உங்கள் கேள்வியைப் பேசுங்கள்",
    photoLabel: "புகைப்படம் எடுக்கவும்",
    photoHint: "நோட்டீஸின் புகைப்படம் எடுக்கவும்",
    emptyState: "கீழே உள்ள பதிவு பொத்தானை அழுத்தி உங்கள் கேள்வியைப் பேசுங்கள்",
    listening: "கேட்டுக்கொண்டிருக்கிறேன்…",
    thinking: "சட்டம் சரிபார்க்கப்படுகிறது…",
    connected: "CONNECTED",
  },
  "te-IN": {
    appName: "న్యాయ-దోస్త్",
    tagline: "మీ చట్టపరమైన హక్కులను మీ స్వంత భాషలో వినండి",
    speakLabel: "మాట్లాడండి",
    speakHint: "నొక్కి మీ ప్రశ్న చెప్పండి",
    photoLabel: "ఫోటో తీయండి",
    photoHint: "నోటీసు ఫోటో తీయండి",
    emptyState: "కింద ఉన్న రికార్డ్ బటన్ నొక్కి మీ ప్రశ్న చెప్పండి",
    listening: "వింటున్నాను…",
    thinking: "చట్టం పరిశీలిస్తోంది…",
    connected: "CONNECTED",
  },
};
